export * from './Home'
export * from './notFound'
export * from './AddProduct'
export * from './Details'
export * from './RegisterForm'
export * from './Profile'
export * from './AdminPanel'
export * from './'