export * from './AdminPanel';
export * from './Details';
export * from './Home';
export * from './LoginPage';
export * from './Profile';
export * from './RegisterForm';
export * from './notFound';
export * from './SearchResults'
export * from "./AppointmentSummary"
