export * from './Home'
export * from './notFound'
export * from './AddProduct'
export * from './Details'
export * from './AdminPanel'
export * from './RegisterForm'
export * from './AdminDoctors'
export * from './AdminFeatures'
export * from './AdminSpecialties'
export * from './AddFeature'
export * from './AddSpecialty'
export * from './UpdateProduct'
export * from './LoginPage'
export * from './Profile'

