export const ROUTES = {
    HOME: "/",
    ADMIN: "/admin",
    DOCTORSADD: "/admin/doctors/add",
    DETAIL: "/doctors/:id",
    ADDUSER: "/register",
    LOGIN: "/login",
    DOCTORS: "/admin/doctors",
    SPECIALTIES: "/admin/specialties",
    FEATURES: "/admin/features",
    PROFILE: "/profile",
    APPOINTMENTS: "/profile/appointments",
    APPOINTMENTSUMMARY: "/appointmentsummary",
    FAVORITES: "/profile/favorites",
    SEARCHHISTORY: "/profile/searchhistory",
    FEATURESADD: "/admin/features/add",
    SPECIALTIESADD: "/admin/specialties/add",
    DOCTORSUPDATE: "/admin/doctors/update/:id",
    FEATURESUPDATE: "/admin/features/update/:id",
    SPECIALTIESUPDATE: "/admin/specialty/update/:id",
    SEARCH: "/search",
    SEARCHRESULTS: "/results"
};